### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by Mingk42** [1-Stone-3-Birds/SB_Works#11]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/root2/.pyenv/versions/3.8.19/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/root2/.pyenv/versions/3.8.19/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "chat.py", line 57, in conchat
    print(f"[{data['user']}]:[{datetime.fromtimestamp(data['time'])}] {data['message']}")
KeyError: 'user'

**Comment by Mingk42** [comment]
- 테스트 과정에서 key로 name과 user가 혼용됨
- topic 변경하여 해결되었습니다.
